server:
  port: ${PORT:8765}
  public-port: ${PUBLIC_PORT:${server.port}}
management:
  server:
    port: ${server.public-port}
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: bookingApi
          uri: lb://BOOKING
          predicates:
            - Path=/api/booking/**
            - Path=/api/rooms/**
        - id: complaintApi
          uri: lb://COMPLAINT
          predicates:
            - Path=/api/complaints/**
            - Path=/api/reviews/**
        - id: guestApi
          uri: lb://GUEST
          predicates:
            - Path=/api/guests/**
        - id: operationApi
          uri: lb://OPERATION
          predicates:
            - Path=/api/occupied-rooms/**
            - Path=/api/operations/**
            - Path=/api/operation-type/**
        - id: staffApi
          uri: lb://STAFF
          predicates:
            - Path=/api/staff-types/**
            - Path=/api/staff/**
  security:
    user:
      password: ${eureka.password}
eureka:
  instance:
    appname: gateway
    nonSecurePort: ${server.public-port}
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: roomsApi
          uri: lb://complain_handling/rooms
          predicates:
            - Path=/api/rooms/**
        - id: complaintApi
          uri: lb://complain_handling/complaint
          predicates:
            - Path=/api/complaint/**
        - id: operationsApi
          uri: lb://guest/api/operations
          predicates:
            - Path=/api/operations/**
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
