app:
  clients:
    logsApi: true
    bookingApi: true
    staffRatingApi: true

feign:
  httpclient:
    enabled: true
server:
  port: ${PORT:8082}
  public-port: ${PUBLIC_PORT:${server.port}}
management:
  server:
    port: ${server.public-port}
spring:
  main:
    banner-mode: off
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  security:
    user:
      password: ${eureka.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
eureka:
  instance:
    appname: OPERATION
    nonSecurePort: ${server.public-port}
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: prod
  h2:
    console.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}

