name: asciidoctor-ghpages

on:
  push:
    branches: [ master, main, fature/add_docs ]
  pull_request:
    branches: [ master, main, fature/add_docs ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          # asciidoctor_params: --attribute=nofooter
          pdf_build: true
          # adoc_file_ext: .ascii # default is .adoc
          # source_dir: docs/ # default is .
          # slides_build: true
          # pre_build:
          # post_build: